# ---------------- #
#   Configurations principales   #
# ---------------- #
baseurl:
url: https://phanremy.github.io
date_format: "ordinal"
title: "Phan Remy"
subtitle: "Ma vie sur Rails"
description: ""
keywords: phan, remy, ruby, rails, developer
timezone: Europe/Paris
encoding: "utf-8"
# Année affichée en bas à gauche de la page
since: 2024
# Dépôt de code source, veuillez remplacer par le vôtre
repository: phanremy/phanremy.github.io
# Configuration de l'accélération CDN pour les ressources CSS et JS
cdn:
    jsdelivr:
        enabled: false
# Configuration des composants optionnels
components:
    # Partage
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: weibo,qq,wechat,douban,qzone
    # Statistiques de visites Busuanzi
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # Mes repo populaires
    side_bar_repo:
        enabled: false
        limit: 5
    # Statistiques du nombre de mots des articles
    word_count:
        enabled: true
    # QR code en haut à droite de la page et sur la page "À propos"
    # Remplacez l'image par `assets/images/qrcode.jpg`
    qrcode:
        enabled: false
        image_alt: Programmeur introverti
    # Vue utilisée pour la page index du Wiki, prend en charge la vue Liste (list) / Catégorie (cate)
    wiki:
        view: cate
    # Effet de lightbox sur les images
    fancybox:
        enabled: false
# Compression du contenu des pages
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# Style de surlignage du code, liste des thèmes supportés disponible sur https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Auteur      #
# ---------------- #
author: Remy Phan
organization:
organization_url:
github_username: phanremy
location: Paris, France
email: phanremy@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Accueil

  -
    href: /categories/
    label: Catégories

  -
    href: /archives/
    label: Archives
    mobile-hidden: true

  -
    href: /open-source/
    label: Open Source
    mobile-hidden: true

  -
    href: /fragments/
    label: Fragments

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Liens
    mobile-hidden: true

  -
    href: /about/
    label: À propos

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # Couleur du texte de la bannière sur la page d'accueil
        color: "#fff"
        # Couleur du texte de la barre de navigation sur la page d'accueil
        nav-color: "rgba(255, 255, 255, .5)"
        # Couleur de fond de la bannière sur la page d'accueil
        background-color: "#4183c4"
        # Image de fond de la bannière sur la page d'accueil
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Commentaires    #
# ---------------- #
# fournisseur supporté : disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!Important!!! Veuillez modifier les informations ci-dessous par les vôtres
# disqus configuration reference: https://disqus.com
disqus:
    username:
# gitment configuration reference: https://imsun.net/posts/gitment-introduction/
# gitalk configuration reference: https://github.com/gitalk/gitalk#install
# utterances configuration reference: https://utteranc.es/
# beaudar configuration reference: https://beaudar.lipk.org/
# giscus configuration reference: https://giscus.app/zh-CN
# Afficher Disqus lorsque d'autres composants de commentaires sont utilisés
lazy_load_disqus : false

# ---------------- #
#      Recherche      #
# ---------------- #
simple_jekyll_search:
    # Prise en charge de la recherche en texte intégral
    fulltext: false
    # Nombre maximum de résultats de recherche affichés
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
